### ISSUE TITLE
psycopg2.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)

### ISSUE THREAD

**Issue by anmolnaik7** [Shubhammalik/Drug-Review-Analysis-Work#2]
![image](https://user-images.githubusercontent.com/56678541/99623655-91fe9e80-2a52-11eb-9987-538e12a31cb8.png)
  File "app.py", line 38, in <module>
    conn = psycopg2.connect(host="localhost", port="5432", user="Shubham", password="", dbname="evoc_core")
  File "C:\Program Files\Python36\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

Using Command Line 

python app.py 
and any way howto start it sir?

**Comment by Shubhammalik** [comment]
Hi Anmol,

I see that you are trying to connect to PostGres Dataset, but I think you are yet to create one, try to install Postgre on you machine and create a dataset manually named Draw in PostGre API interface, and start the sql engine, make sure to keep the port number same here and in connection (in the code its 5432).
Then using the code available in ETL/Data Aggregation/postgresql_db_creation.py, you can merge your data files to that dataset and access it via the code.
You can rename the db to your system name or a name of your choice instead of "Shubham"
A work around it will be to hard code it in the code to fetch the csv files locally from your system.
